version: '3'

services:
  picture-publishing-service:
    build:
      context: .
      dockerfile: Dockerfile-springboot
    ports:
      - "8080:8080"
    networks:
      - spring-postgres
    depends_on:
      - db

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - picture-publishing-service

  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - spring-postgres
    expose:
    - 5432

volumes:
  database_volume:

networks:
  spring-postgres:

