# Use the official Nginx image as the base
FROM nginx:latest

# Copy the HTML, CSS, and JS files to the Nginx server root directory
COPY frontend/ /usr/share/nginx/html

# Expose the default Nginx port (80)
EXPOSE 80