# Use a base image with JDK and Maven
FROM eclipse-temurin:20-jdk-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the pom.xml file
COPY pom.xml .

# Copy the source code
COPY src/ ./src

COPY mvnw .

COPY .mvn .mvn
# Build the application
RUN ./mvnw package -DskipTests

# Use a lightweight base image with JRE
FROM eclipse-temurin:20-jdk-alpine

# # Set the working directory
WORKDIR /app

# # Copy the built JAR file from the builder stage
COPY --from=builder /app/target/picturePublishingService-0.0.1-SNAPSHOT.jar ./app.jar

# Expose the port on which the Spring Boot application runs
EXPOSE 8080

# Set environment variables for database connection
ENV SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/picture-publishing-service?autoCommit=false
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
ENV SPRING_DATASOURCE_USERNAME=postgres
ENV SPRING_DATASOURCE_PASSWORD=a0123654987
ENV SPRING_JPA_DATABASE_PLATFORM = org.hibernate.dialect.PostgreSQLDialect

# Run the Spring Boot application
CMD ["java", "-jar", "app.jar"]
